[project]
name = "f1calendar"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
# Keep compatibility with NixOS 25.11, which only has up to 3.13
requires-python = ">=3.13,<3.14"
dependencies = [
    "bottle",
    "icalendar",
    "requests",
    "waitress",
    "pillow"
]

[tool.setuptools.packages.find]
include = ["f1cal"]

[dependency-groups]
dev = [
    "jupyter",
    "httpie"
]
